# generated by datamodel-codegen:
#   filename:  ramsin_adv.json
#   timestamp: 2023-03-24T01:48:59+00:00

from __future__ import annotations

from ramsin_model_config import RamsinConfig

from typing import List

from pydantic import BaseSettings


class ModelGrids2(BaseSettings):
    class Config(RamsinConfig): pass
    ngrids: int
    if_adap: int
    ihtran: int
    nacoust: int
    ideltat: int
    nstratx: List[int]
    nstraty: List[int]
    nndtrat: List[int]
    nestz1: int
    nstratz1: List[int]
    nestz2: int
    nstratz2: List[int]
    ninest: List[int]
    njnest: List[int]
    nknest: List[int]
    nnsttop: List[int]
    nnstbot: List[int]
    nxtnest: List[int]


class CcattInfo2(BaseSettings):
    class Config(RamsinConfig): pass
    split_method: str
    chemistry_aq: int
    recycle_tracers: int
    def_proc_src: str
    diur_cycle: List[int]
    na_extra2d: int
    na_extra3d: int
    plumerise: int
    prfrq: float
    volcanoes: int
    mech: int


class TebSpmInfo(BaseSettings):
    class Config(RamsinConfig): pass
    teb_spm: int


class ModelFileInfo2(BaseSettings):
    class Config(RamsinConfig): pass
    nud_type: int
    vwait1: float
    vwaittot: float
    nud_hfile: str
    ramp: float
    timewindowiau: float
    iclobber: int
    ihistdel: int
    wt_nudge_grid: List[float]
    wt_nudge_uv: float
    wt_nudge_th: float
    wt_nudge_pi: float
    wt_nudge_rt: float
    applyiau: int
    filenameiau: str
    timstr: float
    hfilin: str
    ipastin: int
    pastfn: str
    kwrite: int
    frqprt: float
    initfld: int
    itoptflg: List[int]
    isstflg: List[int]
    ivegtflg: List[int]
    isoilflg: List[int]
    ndviflg: List[int]
    nofilflg: List[int]
    iupdndvi: int
    iupdsst: int
    itopsflg: List[int]
    toptenh: List[float]
    toptwvl: List[float]
    iz0flg: List[int]
    z0max: List[float]
    z0fact: float
    mkcoltab: int
    coltabfn: str
    mapaotfile: str
    julesin: str


class ModelOptions2(BaseSettings):
    class Config(RamsinConfig): pass
    dyncore_flag: int
    advmnt: int
    pd_or_mnt_constraint: int
    order_h: int
    order_v: int
    ghostzonelength: int
    icorflg: int
    vveldamp: int
    iexev: int
    imassflx: int
    ibnd: int
    jbnd: int
    cphas: float
    lsflg: int
    nfpt: int
    distim: float
    raddatfn: str
    lonrad: int
    g3d_spread: int
    wcldbs: float
    npatch: int
    nvegpat: int
    nvgcon: int
    pctlcon: float
    nslcon: int
    zrough: float
    albedo: float
    seatmp: float
    dthcon: float
    drtcon: float
    soil_moist: str
    slz: List[float]
    slmstr: List[float]
    stgoff: List[float]
    idiffk: List[int]
    ihorgrad: int
    csx: List[float]
    csz: List[float]
    xkhkm: List[float]
    zkhkm: List[float]
    akmin: List[float]
    irime: int
    iplaws: int
    icloud: int
    idriz: int
    irain: int
    ipris: int
    isnow: int
    iaggr: int
    igraup: int
    ihail: int
    cparm: float
    rparm: float
    pparm: float
    sparm: float
    aparm: float
    gparm: float
    hparm: float
    dparm: float
    gnu: List[float]


class ModelSound(BaseSettings):
    class Config(RamsinConfig): pass
    ipsflg: int
    itsflg: int
    irtsflg: int
    iusflg: int
    hs: float
    ps: List[float]
    ts: List[float]
    rts: List[float]
    us: List[float]
    vs: List[float]


class ModelPrint(BaseSettings):
    class Config(RamsinConfig): pass
    nplt: int
    iplfld: List[str]
    ixsctn: List[int]
    isbval: List[int]


class IsanControl2(BaseSettings):
    class Config(RamsinConfig): pass
    guess1st: str
    iszstage: int
    ivrstage: int
    i1st_flg: int
    iupa_flg: int
    isfc_flg: int
    iarawi: str
    iasrfce: str
    ioflgisz: int
    ioflgvar: int


class IsanIsentropic2(BaseSettings):
    class Config(RamsinConfig): pass
    nisn: int
    levth: List[int]
    nigrids: int
    topsigz: float
    hybbot: float
    hybtop: float
    sfcinf: float
    sigzwt: float
    nfeedvar: int
    maxsta: int
    maxsfc: int
    notsta: int
    notid: str
    iobswin: int
    stasep: float
    igridfl: int
    gridwt: List[float]
    gobsep: float
    gobrad: float
    wvlnth: List[float]
    swvlnth: List[float]
    respon: List[float]
    dlimit: List[float]
    ulimit: List[float]
    ccgradswrite: int
    icgradsprefix: str


class Digitalfilter(BaseSettings):
    class Config(RamsinConfig): pass
    applydigitalfilter: bool
    digitalfiltertimewindow: float


class Meteogram(BaseSettings):
    class Config(RamsinConfig): pass
    applymeteogram: bool
    meteogramfreq: float
    meteogrammap: str
    meteogramdir: str


class RamsinAdvanced(BaseSettings):
    class Config(RamsinConfig): pass
    model_grids2: ModelGrids2
    ccatt_info2: CcattInfo2
    teb_spm_info: TebSpmInfo
    model_file_info2: ModelFileInfo2
    model_options2: ModelOptions2
    model_sound: ModelSound
    model_print: ModelPrint
    isan_control2: IsanControl2
    isan_isentropic2: IsanIsentropic2
    digitalfilter: Digitalfilter
    meteogram: Meteogram
