#!/bin/bash
RAMSIN_BASIC=${RAMSIN_BASIC:-RAMSIN_BASIC}

export RAMSIN_EXPNME="Experiment"
export RAMSIN_TIMMAX=24
export RAMSIN_IMONTH1=09
export RAMSIN_IDATE1=06
export RAMSIN_IYEAR1=2022
export RAMSIN_DTLONG=30.

DATE=${RAMSIN_IYEAR1}${RAMSIN_IMONTH1}${RAMSIN_IDATE1}
JOBNAME=${RAMSIN_EXPNME}-${DATE}-${RAMSIN_TIMMAX}h
JOBDIR=${RAMSIN_EXPNME}/${DATE}-${RAMSIN_TIMMAX}h
SCRATCH=./

# For dataout only
OUTPREFIX=${SCRATCH}${JOBDIR}-dataout
# For datain, datafix, tables
INPREFIX=${SCRATCH}/CEMPA

mkdir -p $OUTPREFIX

export RAMSIN_VARFPFX="${OUTPREFIX}/IVAR/FRN"
export RAMSIN_HFILOUT="${OUTPREFIX}/HIS/FRN"
export RAMSIN_AFILOUT="${OUTPREFIX}/ANL/FRN"
export RAMSIN_TOPFILES="${OUTPREFIX}/SFC/top_OQ3g_FRN"
export RAMSIN_SFCFILES="${OUTPREFIX}/SFC/sfc_OQ3g_FRN"
export RAMSIN_SSTFPFX="${OUTPREFIX}/SFC/sst_OQ3g_FRN"
export RAMSIN_NDVIFPFX="${OUTPREFIX}/SFC/ndv_OQ3g_FRN"
export RAMSIN_FRQANL=30.
export RAMSIN_IVEGTFN="/home/oper/prevtempo/datafix/MapBiomas/Bio+LU"
export RAMSIN_ISSTFN="/home/oper/prevtempo/datain/sst_week/W"
export RAMSIN_ISOILFN="${INPREFIX}/datafix_model/GL_FAO_INPE/FAO"
export RAMSIN_NDVIFN="${INPREFIX}/datafix_model/NDVI-MODIS_GRADS/N"
export RAMSIN_ITOPTFN="${INPREFIX}/datafix_model/topo1km/EL"
export RAMSIN_USMODEL_IN=""
export RAMSIN_USDATA_IN="${INPREFIX}/dados/SOIL_MOISTURE/dados_JULES/${RAMSIN_IYEAR1}${RAMSIN_IMONTH1}/AM.YYYYMMDD.nc"
export RAMSIN_VARPFX="${OUTPREFIX}/IVAR/FRN"
export RAMSIN_ICFILETYPE=4
export RAMSIN_ICPREFIX="${SCRATCH}/mateusff/GRADS/${DATE}00/IC"
export RAMSIN_GPREFIX="${OUTPREFIX}/POST/FRN25KM"

# RAMSIN Advanced
export RAMSIN_COLTABFN="${INPREFIX}/tables/micro/ct2.0"
export RAMSIN_MAPAOTFILE="${INPREFIX}/tables/rad_carma/infMapAOT.vfm"
export RAMSIN_JULESIN="./jules.in"
export RAMSIN_RADDATFN="${INPREFIX}/tables/rad_carma/rad_param.data"
export RAMSIN_ICGRADSPREFIX="${OUTPREFIX}/IC/icGrads"

python3 ramsin_env.py -f "$RAMSIN_BASIC" -o RAMSIN_modified -a RAMSIN_adv_modified