#!/bin/bash
RAMSIN_BASIC=${RAMSIN_BASIC:-RAMSIN_BASIC}

export RAMSIN_MODEL_GRIDS_EXPNME="Experiment"
export RAMSIN_MODEL_GRIDS_TIMMAX=24
export RAMSIN_MODEL_GRIDS_IMONTH1=09
export RAMSIN_MODEL_GRIDS_IDATE1=06
export RAMSIN_MODEL_GRIDS_IYEAR1=2022
export RAMSIN_MODEL_GRIDS_DTLONG=30.

DATE=${RAMSIN_MODEL_GRIDS_IYEAR1}${RAMSIN_MODEL_GRIDS_IMONTH1}${RAMSIN_MODEL_GRIDS_IDATE1}
JOBNAME=${RAMSIN_MODEL_GRIDS_EXPNME}-${DATE}-${RAMSIN_MODEL_GRIDS_TIMMAX}h
JOBDIR=${RAMSIN_MODEL_GRIDS_EXPNME}/${DATE}-${RAMSIN_MODEL_GRIDS_TIMMAX}h
SCRATCH=./

# For dataout only
OUTPREFIX=${SCRATCH}/${JOBDIR}-dataout
# For datain, datafix, tables
INPREFIX=${SCRATCH}/CEMPA

mkdir -p $OUTPREFIX

export RAMSIN_MODEL_FILE_INFO_VARFPFX="'${OUTPREFIX}/IVAR/FRN'"
export RAMSIN_MODEL_FILE_INFO_HFILOUT="'${OUTPREFIX}/HIS/FRN'"
export RAMSIN_MODEL_FILE_INFO_AFILOUT="'${OUTPREFIX}/ANL/FRN'"
export RAMSIN_MODEL_FILE_INFO_TOPFILES="'${OUTPREFIX}/SFC/top_OQ3g_FRN'"
export RAMSIN_MODEL_FILE_INFO_SFCFILES="'${OUTPREFIX}/SFC/sfc_OQ3g_FRN'"
export RAMSIN_MODEL_FILE_INFO_SSTFPFX="'${OUTPREFIX}/SFC/sst_OQ3g_FRN'"
export RAMSIN_MODEL_FILE_INFO_NDVIFPFX="'${OUTPREFIX}/SFC/ndv_OQ3g_FRN'"
export RAMSIN_MODEL_FILE_INFO_FRQANL=30.
export RAMSIN_MODEL_FILE_INFO_IVEGTFN="'/home/oper/prevtempo/datafix/MapBiomas/Bio+LU'"
export RAMSIN_MODEL_FILE_INFO_ISSTFN="'/home/oper/prevtempo/datain/sst_week/W'"
export RAMSIN_MODEL_FILE_INFO_ISOILFN="'${INPREFIX}/datafix_model/GL_FAO_INPE/FAO'"
export RAMSIN_MODEL_FILE_INFO_NDVIFN="'${INPREFIX}/datafix_model/NDVI-MODIS_GRADS/N'"
export RAMSIN_MODEL_FILE_INFO_ITOPTFN="'${INPREFIX}/datafix_model/topo1km/EL'"
export RAMSIN_MODEL_OPTIONS_USMODEL_IN="''"
export RAMSIN_MODEL_OPTIONS_USDATA_IN="'${INPREFIX}/dados/SOIL_MOISTURE/dados_JULES/${RAMSIN_MODEL_GRIDS_IYEAR1}${RAMSIN_MODEL_GRIDS_IMONTH1}/AM.YYYYMMDD.nc'"
export RAMSIN_ISAN_CONTROL_VARPFX="'${OUTPREFIX}/IVAR/FRN'"
export RAMSIN_ISAN_ISENTROPIC_ICFILETYPE=4
export RAMSIN_ISAN_ISENTROPIC_ICPREFIX="'${SCRATCH}/mateusff/GRADS/${DATE}00/IC'"
export RAMSIN_POST_GPREFIX="'${OUTPREFIX}/POST/FRN25KM'"

# RAMSIN Advanced
export RAMSIN_MODEL_FILE_INFO2_COLTABFN="'${INPREFIX}/tables/micro/ct2.0'"
export RAMSIN_MODEL_FILE_INFO2_MAPAOTFILE="'${INPREFIX}/tables/rad_carma/infMapAOT.vfm'"
export RAMSIN_MODEL_FILE_INFO2_JULESIN="'./jules.in'"
export RAMSIN_MODEL_OPTIONS2_RADDATFN="'${INPREFIX}/tables/rad_carma/rad_param.data'"
export RAMSIN_ISAN_ISENTROPIC2_ICGRADSPREFIX="'${OUTPREFIX}/IC/icGrads'"

python3 main.py -f "$RAMSIN_BASIC" -o RAMSIN_modified -a RAMSIN_adv_modified